name: Test Workflow
on:
  # allows manual trigger of worklaod
  workflow_dispatch:
  # will trigger on PR merge to main branch
  push:
    branches: ["main"]

jobs:
  greet-the-world:
    runs-on: ubuntu-latest
    steps:
    - name: Hello
      run: echo "Hello, World! It's a nice day!"
